export const FETCHING_COORDINATE_REQUEST = 'FETCHING_DATA_REQUEST';
export const FETCHING_COORDINATE_SUCCESS = 'FETCHING_DATA_SUCCESS';
export const FETCHING_COORDINATE_FAILURE = 'FETCHING_DATA_FAILURE';
export const FETCHING_PLACE_SUCCESS = 'FETCHING_PLACE_SUCCESS';
export const FETCHING_COUPONS_SUCCESS = 'FETCHING_COUPONS_SUCCESS';
export const FETCHING_DETAILS_COUPON_SUCCESS = 'FETCHING_DETAILS_COUPON_SUCCESS';

